# Generated by Django 5.2.1 on 2025-05-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
